server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music_catalog 
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "3f8c2a1b9d4e7f0a2c5b8e1d4f7a0c3b6e9f2a5d8b1c4e7f0a3b6d9c2e5f8a1b"
