server:
  port: 8083

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: music-tracks

jwt:
  secret: ${JWT_SECRET:default-dev-secret}